spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:G:/tools/sqlite-tools-win32-x86-3240000/ventas.db
  jackson:
    default-property-inclusion: non-absent
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
        format_sql: true